name 'xdrum-puppet'
version '0.0.4'
source 'git://github.com/x-drum/puppet-puppet'
author 'Alessio Cassibba (X-Drum)'
license 'Apache 2.0'
summary 'Puppet Module'
description "Configure and install puppet for agent and master nodes."
project_page 'https://github.com/x-drum/puppet-puppet'
dependency 'puppetlabs-apache', '>= 1.0.1'
dependency 'puppetlabs-inifile', '>= 1.0.3'
dependency 'example42-yum', '>= 2.1.10'
